name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - name: Install apt dependencies
        run: sudo apt-get update && sudo apt-get install -y ninja-build g++-12

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: pip install 'poetry<2.0'

      - name: Cache Conan packages
        id: cache-conan
        uses: actions/cache@v4
        with:
          path: ~/.conan2/p
          key: conan-build-${{ runner.os }}-${{ hashFiles('ci/conan-vitasdk/conanfile.py', 'ci/conan-fmt/conanfile.py', 'ci/conan-libzip/conanfile.py', 'ci/conan-vitasqlite/conanfile.py', 'conanfile.py') }}
          restore-keys: conan-build-${{ runner.os }}-

      - run: ci/ci.sh

      - name: Upload linux build
        uses: actions/upload-artifact@v4
        with:
          name: pkgj_cli
          path: ci/buildhost/pkgj_cli

      - name: Upload vita build
        uses: actions/upload-artifact@v4
        with:
          name: UsagiPKGJ.vpk
          path: ci/build/UsagiPKGJ.vpk
